// File generated by FlutterFire CLI.
// ignoreForFile: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDDKmBY_WLpo32pAQk8asa3jBTaM2D690k',
  appId: '1:728614601825:android:fba7584751ae0f18589620',
  messagingSenderId: '728614601825',
  projectId: 'chanakya-connect',
  storageBucket: 'chanakya-connect.firebasestorage.app',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with your API key
    appId: 'YOUR_IOS_APP_ID', // Replace with your app ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Replace with your messaging sender ID
    projectId: 'YOUR_PROJECT_ID', // Replace with your project ID
    databaseURL: 'YOUR_DATABASE_URL', // Optional
    storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your storage bucket
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Replace with your API key
    appId: 'YOUR_WEB_APP_ID', // Replace with your app ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Replace with your messaging sender ID
    projectId: 'YOUR_PROJECT_ID', // Replace with your project ID
    authDomain: 'YOUR_AUTH_DOMAIN', // Replace with your auth domain
    databaseURL: 'YOUR_DATABASE_URL', // Optional
    storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your storage bucket
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with your API key
    appId: 'YOUR_MACOS_APP_ID', // Replace with your app ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // Replace with your messaging sender ID
    projectId: 'YOUR_PROJECT_ID', // Replace with your project ID
    databaseURL: 'YOUR_DATABASE_URL', // Optional
    storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your storage bucket
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Replace with your API key
    appId: 'YOUR_WINDOWS_APP_ID', // Replace with your app ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // 
    projectId: 'YOUR_PROJECT_ID', // Replace with your project ID
    authDomain: 'YOUR_AUTH_DOMAIN', // Replace with your auth domain
    databaseURL: 'YOUR_DATABASE_URL', // Optional
    storageBucket: 'YOUR_STORAGE_BUCKET', // Replace with your storage bucket
  );
}
